name: Snyk Security Vulnerability Scan

on:
  pull_request:
  push:
    tags:
      - 'v.[0-9]+.[0-100]+.[0-100]+'
    branches:
      - 'master'

jobs:
  snyk_scan_test:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2

      - name: Check changed Deps files
        uses: tj-actions/changed-files@v10
        id: changed-files
        with:
          files: |
              build.gradle
              common/jdbc/build.gradle
              gcp-cloud-run/build.gradle
              common/kdb-java/build.gradle
              kdb-mojo-scorer/build.gradle
              sql-jdbc-scorer/build.gradle
              common/transform/build.gradle
              local-rest-scorer/build.gradle
              common/rest-java-model/build.gradle
              common/rest-spring-api/build.gradle
              gcp-vertex-ai-mojo-scorer/build.gradle
              aws-sagemaker-hosted-scorer/build.gradle
              common/rest-jdbc-spring-api/build.gradle
              common/rest-vertex-ai-spring-api/build.gradle
              aws-lambda-scorer/lambda-template/build.gradle
              aws-lambda-scorer/terraform-recipe/build.gradle

      - uses: snyk/actions/setup@master
      - uses: actions/setup-java@v1
        with:
          java-version: "8"
          distribution: 'adopt'

      - name: Snyk scan for Java dependancies - h2o-mli/build.gradle
        if: contains(steps.changed-files.outputs.any_changed)
        run: snyk test --all-projects -d --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

#      - name: Snyk scan for Java dependancies - h2o-mli/mli-algos/build.gradle
#        if: contains(steps.changed-files.outputs.all_changed_and_modified_files, 'h2o-mli/mli-algos/build.gradle')
#        id: scan2
#        run: snyk test --file=mli-algos/build.gradle -d --fail-on=all
#        continue-on-error: true
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#
#      - name: Snyk scan for Java dependancies - h2o-mli/mli-backend/build.gradle
#        if: contains(steps.changed-files.outputs.all_changed_and_modified_files, 'h2o-mli/mli-backend/build.gradle')
#        id: scan3
#        run: snyk test --file=mli-backend/build.gradle  -d --fail-on=all
#        continue-on-error: true
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#
#      - name: Check on Snyk scan failures
#        if: steps.scan1.outcome == 'failure' || steps.scan2.outcome == 'failure' || steps.scan3.outcome == 'failure'
#        run: |
#          echo "[warning] Please solve the fixable security vulnerabilities found in failed steps!
#                h2o-mli/build.gradle - ${{ steps.scan1.outcome }}
#                h2o-mli/mli-algos/build.gradle - ${{ steps.scan2.outcome }}
#                h2o-mli/mli-backend/build.gradle - ${{ steps.scan3.outcome }}"
#          exit 1

  snyk_scan_monitor:
    #if: ${{ github.event_name == 'push' }}
    strategy:
      matrix:
        depsfiles: [
          build.gradle,
          common/jdbc/build.gradle,
          gcp-cloud-run/build.gradle,
          common/kdb-java/build.gradle,
          kdb-mojo-scorer/build.gradle,
          sql-jdbc-scorer/build.gradle,
          common/transform/build.gradle,
          local-rest-scorer/build.gradle,
          common/rest-java-model/build.gradle,
          common/rest-spring-api/build.gradle,
          gcp-vertex-ai-mojo-scorer/build.gradle,
          aws-sagemaker-hosted-scorer/build.gradle,
          common/rest-jdbc-spring-api/build.gradle,
          common/rest-vertex-ai-spring-api/build.gradle,
          aws-lambda-scorer/lambda-template/build.gradle,
          aws-lambda-scorer/terraform-recipe/build.gradle
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract github branch/tag name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref

      - uses: snyk/actions/setup@master
      - uses: actions/setup-java@v1
        with:
          java-version: "8"
          distribution: 'adopt'

      - name: Snyk scan for Java dependancies - ${{ matrix.depsfiles }}
        run: snyk monitor --org=h2oai --remote-repo-url=DAI --file=${{ matrix.depsfiles }} --project-name=DAI/dai-deployment-templates/${{ steps.extract_ref.outputs.ref }}/${{ matrix.depsfiles }} -d
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

#      - name: Snyk scan for Java dependancies - h2o-mli/mli-algos/build.gradle
#        run: snyk monitor --org=h2oai --remote-repo-url=DAI --file=mli-algos/build.gradle --project-name=DAI/mli/${{ steps.extract_ref.outputs.ref }}/h2o-mli/mli-algos/build.gradle -d
#        continue-on-error: true
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
#
#      - name: Snyk scan for Java dependancies - h2o-mli/mli-backend/build.gradle
#        run: snyk monitor --org=h2oai --remote-repo-url=DAI --file=mli-backend/build.gradle --project-name=DAI/mli/${{ steps.extract_ref.outputs.ref }}/h2o-mli/mli-backend/build.gradle -d
#        continue-on-error: true
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
